/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd.Vista;

import bd.Modelo.ManejoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author beto
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     * @throws java.sql.SQLException
     */
    public FormularioPrincipal() throws SQLException {
        ManejoBD manbd = new ManejoBD();        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        menuPrincipal = new javax.swing.JMenuBar();
        subMenuAlumno = new javax.swing.JMenu();
        opcionAltaAlumno = new javax.swing.JMenuItem();
        opcionBajaAlumno = new javax.swing.JMenuItem();
        opcionInscripcionMateriaProfesor = new javax.swing.JMenuItem();
        subMenuMateria = new javax.swing.JMenu();
        opcionAltaMateria = new javax.swing.JMenuItem();
        opcionBajaMateria = new javax.swing.JMenuItem();
        opcionListadoAlumnosPorMateriaProfesor = new javax.swing.JMenuItem();
        subMenuProfesor = new javax.swing.JMenu();
        opcionAltaProfesor = new javax.swing.JMenuItem();
        opcionBajaProfesor = new javax.swing.JMenuItem();
        opcionAsignacionProfeAMateria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INSTITUTO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 450));

        subMenuAlumno.setText("Alumnos");
        subMenuAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuAlumnoActionPerformed(evt);
            }
        });

        opcionAltaAlumno.setText("Alta");
        opcionAltaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionAltaAlumnoActionPerformed(evt);
            }
        });
        subMenuAlumno.add(opcionAltaAlumno);

        opcionBajaAlumno.setText("Baja");
        opcionBajaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionBajaAlumnoActionPerformed(evt);
            }
        });
        subMenuAlumno.add(opcionBajaAlumno);

        opcionInscripcionMateriaProfesor.setText("Inscripcion a materia de profesor");
        opcionInscripcionMateriaProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionInscripcionMateriaProfesorActionPerformed(evt);
            }
        });
        subMenuAlumno.add(opcionInscripcionMateriaProfesor);

        menuPrincipal.add(subMenuAlumno);

        subMenuMateria.setText("Materias");

        opcionAltaMateria.setText("Alta");
        opcionAltaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionAltaMateriaActionPerformed(evt);
            }
        });
        subMenuMateria.add(opcionAltaMateria);

        opcionBajaMateria.setText("Baja");
        opcionBajaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionBajaMateriaActionPerformed(evt);
            }
        });
        subMenuMateria.add(opcionBajaMateria);

        opcionListadoAlumnosPorMateriaProfesor.setText("Listado de alumnos por materia profesor");
        opcionListadoAlumnosPorMateriaProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionListadoAlumnosPorMateriaProfesorActionPerformed(evt);
            }
        });
        subMenuMateria.add(opcionListadoAlumnosPorMateriaProfesor);

        menuPrincipal.add(subMenuMateria);

        subMenuProfesor.setText("Profesores");

        opcionAltaProfesor.setText("Alta");
        opcionAltaProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionAltaProfesorActionPerformed(evt);
            }
        });
        subMenuProfesor.add(opcionAltaProfesor);

        opcionBajaProfesor.setText("Baja");
        opcionBajaProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionBajaProfesorActionPerformed(evt);
            }
        });
        subMenuProfesor.add(opcionBajaProfesor);

        opcionAsignacionProfeAMateria.setText("Asignacion profesor a materias");
        opcionAsignacionProfeAMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionAsignacionProfeAMateriaActionPerformed(evt);
            }
        });
        subMenuProfesor.add(opcionAsignacionProfeAMateria);

        menuPrincipal.add(subMenuProfesor);

        setJMenuBar(menuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuAlumnoActionPerformed
        VentanaAltaAlumnoAMateriaProfesor ventanaInscripcionMateriaProfesor = new VentanaAltaAlumnoAMateriaProfesor();
        this.PanelPrincipal.add(ventanaInscripcionMateriaProfesor);
        ventanaInscripcionMateriaProfesor.show();
    }//GEN-LAST:event_subMenuAlumnoActionPerformed

    private void opcionBajaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBajaAlumnoActionPerformed
        VentanaBajaAlumno ventanaBajaAlumno = new VentanaBajaAlumno();
        this.PanelPrincipal.add(ventanaBajaAlumno);
        ventanaBajaAlumno.show();
    }//GEN-LAST:event_opcionBajaAlumnoActionPerformed

    private void opcionAltaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionAltaAlumnoActionPerformed
        VentanaAltaAlumno ventanaAltaAlumno = new VentanaAltaAlumno();
        this.PanelPrincipal.add(ventanaAltaAlumno);
        ventanaAltaAlumno.show();
    }//GEN-LAST:event_opcionAltaAlumnoActionPerformed

    private void opcionInscripcionMateriaProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionInscripcionMateriaProfesorActionPerformed
        VentanaAltaAlumnoAMateriaProfesor ventanaAltaMateriaProfesor = new VentanaAltaAlumnoAMateriaProfesor();
        this.PanelPrincipal.add(ventanaAltaMateriaProfesor);
        ventanaAltaMateriaProfesor.show();
    }//GEN-LAST:event_opcionInscripcionMateriaProfesorActionPerformed

    private void opcionAltaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionAltaMateriaActionPerformed
        VentanaAltaMateria ventanaAltaMateria = new VentanaAltaMateria();
        this.PanelPrincipal.add(ventanaAltaMateria);
        ventanaAltaMateria.show();
    }//GEN-LAST:event_opcionAltaMateriaActionPerformed

    private void opcionBajaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBajaMateriaActionPerformed
        VentanaBajaMateria ventanaBajaMateria = new VentanaBajaMateria();
        this.PanelPrincipal.add(ventanaBajaMateria);
        ventanaBajaMateria.show();
    }//GEN-LAST:event_opcionBajaMateriaActionPerformed

    private void opcionAltaProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionAltaProfesorActionPerformed
        VentanaAltaProfesor ventanaAltaProfesor = new VentanaAltaProfesor();
        this.PanelPrincipal.add(ventanaAltaProfesor);
        ventanaAltaProfesor.show();
    }//GEN-LAST:event_opcionAltaProfesorActionPerformed

    private void opcionBajaProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBajaProfesorActionPerformed
        VentanaBajaProfesor ventanaBajaProfesor = new VentanaBajaProfesor();
        this.PanelPrincipal.add(ventanaBajaProfesor);
        ventanaBajaProfesor.show();                
    }//GEN-LAST:event_opcionBajaProfesorActionPerformed

    private void opcionAsignacionProfeAMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionAsignacionProfeAMateriaActionPerformed
        VentanaAltaProfeAMateria ventanaAltaProfeMateria = new VentanaAltaProfeAMateria();
        this.PanelPrincipal.add(ventanaAltaProfeMateria);
        ventanaAltaProfeMateria.show();
    }//GEN-LAST:event_opcionAsignacionProfeAMateriaActionPerformed

    private void opcionListadoAlumnosPorMateriaProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionListadoAlumnosPorMateriaProfesorActionPerformed
        VentanaListadoAlumnosPorMateria ventanaListadoAlumnosPorMateria = new VentanaListadoAlumnosPorMateria();
        this.PanelPrincipal.add(ventanaListadoAlumnosPorMateria);
        ventanaListadoAlumnosPorMateria.show();
    }//GEN-LAST:event_opcionListadoAlumnosPorMateriaProfesorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new FormularioPrincipal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenuItem opcionAltaAlumno;
    private javax.swing.JMenuItem opcionAltaMateria;
    private javax.swing.JMenuItem opcionAltaProfesor;
    private javax.swing.JMenuItem opcionAsignacionProfeAMateria;
    private javax.swing.JMenuItem opcionBajaAlumno;
    private javax.swing.JMenuItem opcionBajaMateria;
    private javax.swing.JMenuItem opcionBajaProfesor;
    private javax.swing.JMenuItem opcionInscripcionMateriaProfesor;
    private javax.swing.JMenuItem opcionListadoAlumnosPorMateriaProfesor;
    private javax.swing.JMenu subMenuAlumno;
    private javax.swing.JMenu subMenuMateria;
    private javax.swing.JMenu subMenuProfesor;
    // End of variables declaration//GEN-END:variables
}
