/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd.Vista;

import bd.Modelo.ManejoBD;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author beto
 */
public class VentanaAltaProfeAMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form AltaProfeAMateria
     */
    public VentanaAltaProfeAMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_Alta_ID_Profe_A_Materia = new javax.swing.JTextField();
        jlbl_TItuloAltaProfeAMateria = new javax.swing.JLabel();
        jlbl_Ingresar_Codigo_Alta_Profe_Materia = new javax.swing.JLabel();
        jlbl_Materia_Alta_Profe_Materia = new javax.swing.JLabel();
        jcbx_Todas_Materias = new javax.swing.JComboBox<>();
        jbtn_Aceptar_Alta_Profe_Materia = new javax.swing.JButton();
        jbtn_Cancelar_Alta_Profe_Materia = new javax.swing.JButton();

        jlbl_TItuloAltaProfeAMateria.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jlbl_TItuloAltaProfeAMateria.setText("Asignacion Profesor a Materia");

        jlbl_Ingresar_Codigo_Alta_Profe_Materia.setText("Ingrese codigo de profe:");

        jlbl_Materia_Alta_Profe_Materia.setText("Ingrese materia:");

        jcbx_Todas_Materias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una materia..." }));
        jcbx_Todas_Materias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbx_Todas_MateriasActionPerformed(evt);
            }
        });

        jbtn_Aceptar_Alta_Profe_Materia.setText("Aceptar");
        jbtn_Aceptar_Alta_Profe_Materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_Aceptar_Alta_Profe_MateriaActionPerformed(evt);
            }
        });

        jbtn_Cancelar_Alta_Profe_Materia.setText("Cancelar");
        jbtn_Cancelar_Alta_Profe_Materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_Cancelar_Alta_Profe_MateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jlbl_TItuloAltaProfeAMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbl_Materia_Alta_Profe_Materia)
                                .addGap(26, 26, 26)
                                .addComponent(jcbx_Todas_Materias, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbl_Ingresar_Codigo_Alta_Profe_Materia)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_Alta_ID_Profe_A_Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtn_Aceptar_Alta_Profe_Materia)
                .addGap(29, 29, 29)
                .addComponent(jbtn_Cancelar_Alta_Profe_Materia)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlbl_TItuloAltaProfeAMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Alta_ID_Profe_A_Materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_Ingresar_Codigo_Alta_Profe_Materia))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_Materia_Alta_Profe_Materia)
                    .addComponent(jcbx_Todas_Materias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Aceptar_Alta_Profe_Materia)
                    .addComponent(jbtn_Cancelar_Alta_Profe_Materia))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_Cancelar_Alta_Profe_MateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_Cancelar_Alta_Profe_MateriaActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_Cancelar_Alta_Profe_MateriaActionPerformed

    private void jcbx_Todas_MateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbx_Todas_MateriasActionPerformed
        ManejoBD manbd = new ManejoBD();           
        try {
            ArrayList<String> arraylito2 = manbd.consultarMaterias();
            //this.jcbx_Todas_Materias.removeAllItems();
            for(int i=0; i<arraylito2.size(); i++){                
                this.jcbx_Todas_Materias.addItem(arraylito2.get(i));
            }            
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Un error ha ocurrido!: " + ex);
        }       
    }//GEN-LAST:event_jcbx_Todas_MateriasActionPerformed

    private void jbtn_Aceptar_Alta_Profe_MateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_Aceptar_Alta_Profe_MateriaActionPerformed
        ManejoBD manbd = new ManejoBD();
        try{
            //mando id_profe y nombreMateria seleccionado
            manbd.altaProfeAMateria(this.jtf_Alta_ID_Profe_A_Materia.getText(), this.jcbx_Todas_Materias.getSelectedItem().toString());
        }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null, "Un error ha ocurrido!: " + e);
        }    
        
    }//GEN-LAST:event_jbtn_Aceptar_Alta_Profe_MateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_Aceptar_Alta_Profe_Materia;
    private javax.swing.JButton jbtn_Cancelar_Alta_Profe_Materia;
    private javax.swing.JComboBox<String> jcbx_Todas_Materias;
    private javax.swing.JLabel jlbl_Ingresar_Codigo_Alta_Profe_Materia;
    private javax.swing.JLabel jlbl_Materia_Alta_Profe_Materia;
    private javax.swing.JLabel jlbl_TItuloAltaProfeAMateria;
    private javax.swing.JTextField jtf_Alta_ID_Profe_A_Materia;
    // End of variables declaration//GEN-END:variables
}
