/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd.Vista;

import bd.Modelo.ManejoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author beto
 */
public class VentanaBajaProfesor extends javax.swing.JInternalFrame {

    /**
     * Creates new form BajaProfesor
     */
    public VentanaBajaProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbl_TituloBajaProfesor = new javax.swing.JLabel();
        jlbl_ID_BajaProfesor = new javax.swing.JLabel();
        jtf_ID_BajaProfesor = new javax.swing.JTextField();
        jbtn_AceptarAltaProfesor = new javax.swing.JButton();
        jbtn_CancelarAltaProfesor = new javax.swing.JButton();

        jlbl_TituloBajaProfesor.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jlbl_TituloBajaProfesor.setText("Baja Profesor");

        jlbl_ID_BajaProfesor.setText("ID:");

        jbtn_AceptarAltaProfesor.setText("Aceptar");
        jbtn_AceptarAltaProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_AceptarAltaProfesorActionPerformed(evt);
            }
        });

        jbtn_CancelarAltaProfesor.setText("Cancelar");
        jbtn_CancelarAltaProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_CancelarAltaProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jbtn_AceptarAltaProfesor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_CancelarAltaProfesor))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jlbl_TituloBajaProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jtf_ID_BajaProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlbl_ID_BajaProfesor)
                        .addGap(120, 120, 120))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlbl_TituloBajaProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlbl_ID_BajaProfesor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_ID_BajaProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_AceptarAltaProfesor)
                    .addComponent(jbtn_CancelarAltaProfesor))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_CancelarAltaProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_CancelarAltaProfesorActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_CancelarAltaProfesorActionPerformed

    private void jbtn_AceptarAltaProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_AceptarAltaProfesorActionPerformed
        ManejoBD manbd = new ManejoBD();
        try {
            manbd.bajaProfesor(this.jtf_ID_BajaProfesor.getText());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaBajaProfesor.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_jbtn_AceptarAltaProfesorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_AceptarAltaProfesor;
    private javax.swing.JButton jbtn_CancelarAltaProfesor;
    private javax.swing.JLabel jlbl_ID_BajaProfesor;
    private javax.swing.JLabel jlbl_TituloBajaProfesor;
    private javax.swing.JTextField jtf_ID_BajaProfesor;
    // End of variables declaration//GEN-END:variables
}
