/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd.Vista;

import bd.Modelo.Alumno;
import bd.Modelo.ManejoBD;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author beto
 */
public class VentanaListadoAlumnosPorMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaListadoAlumnosPorMateria
     */
    public VentanaListadoAlumnosPorMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlbl_Ingresar_Materia = new javax.swing.JLabel();
        jcmbx_Todas_Materias = new javax.swing.JComboBox<>();
        jlbl_Listado = new javax.swing.JLabel();
        jlbl_Profesor_Que_Dicta_Materia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_Tabla_Listado_Alumnos_Por_Materia = new javax.swing.JTable();
        jbtn_Cancelar_Listado_Alumnos_Inscriptos_Por_Materia = new javax.swing.JButton();
        jbtn_AceptarListadoAlumnosPorMateriaDeProfesor = new javax.swing.JButton();
        jcbbx_listadoProfesPorMateria = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setText("Listado de alumnos inscriptos por materia");

        jlbl_Ingresar_Materia.setText("Ingrese materia:");

        jcmbx_Todas_Materias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione materia..." }));
        jcmbx_Todas_Materias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbx_Todas_MateriasActionPerformed(evt);
            }
        });

        jlbl_Listado.setText("Listado de alumnos...");

        jlbl_Profesor_Que_Dicta_Materia.setText("Profesor/a:");

        jtbl_Tabla_Listado_Alumnos_Por_Materia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IDAlumno", "Nombre", "Apellido"
            }
        ));
        jScrollPane1.setViewportView(jtbl_Tabla_Listado_Alumnos_Por_Materia);

        jbtn_Cancelar_Listado_Alumnos_Inscriptos_Por_Materia.setText("Cancelar");
        jbtn_Cancelar_Listado_Alumnos_Inscriptos_Por_Materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_Cancelar_Listado_Alumnos_Inscriptos_Por_MateriaActionPerformed(evt);
            }
        });

        jbtn_AceptarListadoAlumnosPorMateriaDeProfesor.setText("Aceptar");
        jbtn_AceptarListadoAlumnosPorMateriaDeProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_AceptarListadoAlumnosPorMateriaDeProfesorActionPerformed(evt);
            }
        });

        jcbbx_listadoProfesPorMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione profesor/a..." }));
        jcbbx_listadoProfesPorMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbx_listadoProfesPorMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtn_AceptarListadoAlumnosPorMateriaDeProfesor)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_Cancelar_Listado_Alumnos_Inscriptos_Por_Materia)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlbl_Listado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jlbl_Ingresar_Materia)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcmbx_Todas_Materias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jlbl_Profesor_Que_Dicta_Materia)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbbx_listadoProfesPorMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_Ingresar_Materia)
                    .addComponent(jcmbx_Todas_Materias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbbx_listadoProfesPorMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_Profesor_Que_Dicta_Materia))
                .addGap(18, 18, 18)
                .addComponent(jlbl_Listado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Cancelar_Listado_Alumnos_Inscriptos_Por_Materia)
                    .addComponent(jbtn_AceptarListadoAlumnosPorMateriaDeProfesor))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_Cancelar_Listado_Alumnos_Inscriptos_Por_MateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_Cancelar_Listado_Alumnos_Inscriptos_Por_MateriaActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_Cancelar_Listado_Alumnos_Inscriptos_Por_MateriaActionPerformed

    private void jcmbx_Todas_MateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbx_Todas_MateriasActionPerformed
        ManejoBD manbd = new ManejoBD();           
        try {
            ArrayList<String> al_Materias_Totales = manbd.consultarMaterias();
            //this.jcb_MateriasTotales.removeAllItems();
            for(int i=0; i<al_Materias_Totales.size(); i++){                
                this.jcmbx_Todas_Materias.addItem(al_Materias_Totales.get(i));
            }            
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Un error ha ocurrido!: " + ex);
        }       
        
    }//GEN-LAST:event_jcmbx_Todas_MateriasActionPerformed

    private void jbtn_AceptarListadoAlumnosPorMateriaDeProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_AceptarListadoAlumnosPorMateriaDeProfesorActionPerformed
        ManejoBD manbd = new ManejoBD();
        //Llenar tabla a partir de materia y profe seleccionados  
        //Item selected combobox materias
        Object obj = this.jcmbx_Todas_Materias.getSelectedItem();
        String materiaSeleccionada = String.valueOf(obj);         
        //Item selected combobox profesores
        Object obj2 = this.jcbbx_listadoProfesPorMateria.getSelectedItem();
        String profesorSeleccionado = String.valueOf(obj2);
            try {
                ArrayList<Alumno> al_listadoAlumnosPorMateria = manbd.consultarListadoAlumnosPorMateriaDeUnProfesor(materiaSeleccionada, profesorSeleccionado); //listado alumnos materia [CORRECTO]
                //Creo tabla auxiliar identica a VentanaTablaListadoAlumnosPorMateria para retornar
                DefaultTableModel modeloTabla = new DefaultTableModel();            
                //Creo AL para titulosColumnas
                ArrayList<String> al_titulos_columnas = new ArrayList<>();
                al_titulos_columnas.add("IDAlumno");
                al_titulos_columnas.add("Nombre");
                al_titulos_columnas.add("Apellido");
                //Agrego titulosColumnas a la tabla
                for(String columna : al_titulos_columnas){    
                    modeloTabla.addColumn(columna);
                }                  
                //Voy recorriendo el AL de alumnos por materia. Para cada objeto del mismo creo un vector el cual guarda los campos de Alumno
                for(int i=0; i<al_listadoAlumnosPorMateria.size(); i++){
                    String[] vector_alu = new String[]{al_listadoAlumnosPorMateria.get(i).getId(), al_listadoAlumnosPorMateria.get(i).getNombre(), al_listadoAlumnosPorMateria.get(i).getApellido() };
                    modeloTabla.addRow(vector_alu);
                }                
                this.jtbl_Tabla_Listado_Alumnos_Por_Materia.setModel(modeloTabla);
                //limpio los combobox
                this.jcmbx_Todas_Materias.removeAllItems();
                this.jcbbx_listadoProfesPorMateria.removeAllItems();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VentanaListadoAlumnosPorMateria.class.getName()).log(Level.SEVERE, null, ex);
            }        
    }//GEN-LAST:event_jbtn_AceptarListadoAlumnosPorMateriaDeProfesorActionPerformed

    private void jcbbx_listadoProfesPorMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbx_listadoProfesPorMateriaActionPerformed
        ManejoBD manbd = new ManejoBD();           
        try {
            ArrayList<String> arraylito2 = manbd.consultarProfesoresQueDictanUnaMateria(this.jcmbx_Todas_Materias.getSelectedItem().toString());
            //this.jcb_PrefesoresDeLaMateriaSeleccionada.removeAllItems();
            for(int i=0; i<arraylito2.size(); i++){                
                this.jcbbx_listadoProfesPorMateria.addItem(arraylito2.get(i));
            }            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Un error ha ocurrido!: " + ex);
        }
    }//GEN-LAST:event_jcbbx_listadoProfesPorMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_AceptarListadoAlumnosPorMateriaDeProfesor;
    private javax.swing.JButton jbtn_Cancelar_Listado_Alumnos_Inscriptos_Por_Materia;
    private javax.swing.JComboBox<String> jcbbx_listadoProfesPorMateria;
    private javax.swing.JComboBox<String> jcmbx_Todas_Materias;
    private javax.swing.JLabel jlbl_Ingresar_Materia;
    private javax.swing.JLabel jlbl_Listado;
    private javax.swing.JLabel jlbl_Profesor_Que_Dicta_Materia;
    private javax.swing.JTable jtbl_Tabla_Listado_Alumnos_Por_Materia;
    // End of variables declaration//GEN-END:variables
}
