/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd.Vista;

import bd.Modelo.ManejoBD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author beto
 */
public class VentanaAltaAlumnoAMateriaProfesor extends javax.swing.JInternalFrame {

    /**
     * Creates new form InscripcionMateriaProfesor
     */
    public VentanaAltaAlumnoAMateriaProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbl_TituloInscripcionMateriaProfesor = new javax.swing.JLabel();
        jlbl_ID_Alumno = new javax.swing.JLabel();
        jlbl_NombreMateria = new javax.swing.JLabel();
        jlbl_Profesor = new javax.swing.JLabel();
        jtf_ID_Alumno = new javax.swing.JTextField();
        jcb_MateriasTotales = new javax.swing.JComboBox<>();
        jbAceptar = new javax.swing.JButton();
        jbSalirInscripcionMateriaProfesor = new javax.swing.JButton();
        jcb_PrefesoresDeLaMateriaSeleccionada = new javax.swing.JComboBox<>();

        setResizable(true);

        jlbl_TituloInscripcionMateriaProfesor.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jlbl_TituloInscripcionMateriaProfesor.setText("Inscripcion de alumnos a materias de profesor");

        jlbl_ID_Alumno.setText("Ingrese código alumno:");

        jlbl_NombreMateria.setText("Ingrese materia:");

        jlbl_Profesor.setText("Ingrese profesor:");

        jcb_MateriasTotales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione materia..." }));
        jcb_MateriasTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_MateriasTotalesActionPerformed(evt);
            }
        });

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jbSalirInscripcionMateriaProfesor.setText("Cancelar");
        jbSalirInscripcionMateriaProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirInscripcionMateriaProfesorActionPerformed(evt);
            }
        });

        jcb_PrefesoresDeLaMateriaSeleccionada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione profesor/a" }));
        jcb_PrefesoresDeLaMateriaSeleccionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_PrefesoresDeLaMateriaSeleccionadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jlbl_Profesor)
                                    .addGap(18, 18, 18)
                                    .addComponent(jcb_PrefesoresDeLaMateriaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jlbl_NombreMateria)
                                    .addGap(18, 18, 18)
                                    .addComponent(jcb_MateriasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jlbl_ID_Alumno)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtf_ID_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(100, 100, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jbAceptar)
                            .addGap(45, 45, 45)
                            .addComponent(jbSalirInscripcionMateriaProfesor)
                            .addGap(22, 22, 22)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlbl_TituloInscripcionMateriaProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlbl_TituloInscripcionMateriaProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_ID_Alumno)
                    .addComponent(jtf_ID_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_NombreMateria)
                            .addComponent(jcb_MateriasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_Profesor)
                            .addComponent(jcb_PrefesoresDeLaMateriaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(72, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbAceptar)
                            .addComponent(jbSalirInscripcionMateriaProfesor))
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirInscripcionMateriaProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirInscripcionMateriaProfesorActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirInscripcionMateriaProfesorActionPerformed

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        ManejoBD manbd = new ManejoBD();
        try{
            manbd.altaAlumnoAMateriaAProfesor(this.jtf_ID_Alumno.getText(), manbd.consultarIDMateriaSegunNombre(this.jcb_MateriasTotales.getSelectedItem().toString()), manbd.consultarIDProfeSegunNombreAprellido(this.jcb_PrefesoresDeLaMateriaSeleccionada.getSelectedItem().toString()));
            //limpio los combobox 
            this.jcb_MateriasTotales.removeAllItems();
            this.jcb_PrefesoresDeLaMateriaSeleccionada.removeAllItems();
        }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null, "Un error ha ocurrido!: " + e);
        }
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jcb_MateriasTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_MateriasTotalesActionPerformed
        ManejoBD manbd = new ManejoBD();           
        try {
            ArrayList<String> al_Materias_Totales = manbd.consultarMaterias();
            //this.jcb_MateriasTotales.removeAllItems();
            for(int i=0; i<al_Materias_Totales.size(); i++){                
                this.jcb_MateriasTotales.addItem(al_Materias_Totales.get(i));
            }            
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Un error ha ocurrido!: " + ex);
        }        
    }//GEN-LAST:event_jcb_MateriasTotalesActionPerformed

    private void jcb_PrefesoresDeLaMateriaSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_PrefesoresDeLaMateriaSeleccionadaActionPerformed
        ManejoBD manbd = new ManejoBD();           
        try {
            ArrayList<String> arraylito2 = manbd.consultarProfesoresQueDictanUnaMateria(this.jcb_MateriasTotales.getSelectedItem().toString());
            //this.jcb_PrefesoresDeLaMateriaSeleccionada.removeAllItems();
            for(int i=0; i<arraylito2.size(); i++){                
                this.jcb_PrefesoresDeLaMateriaSeleccionada.addItem(arraylito2.get(i));
            }            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Un error ha ocurrido!: " + ex);
        }
    }//GEN-LAST:event_jcb_PrefesoresDeLaMateriaSeleccionadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbSalirInscripcionMateriaProfesor;
    private javax.swing.JComboBox<String> jcb_MateriasTotales;
    private javax.swing.JComboBox<String> jcb_PrefesoresDeLaMateriaSeleccionada;
    private javax.swing.JLabel jlbl_ID_Alumno;
    private javax.swing.JLabel jlbl_NombreMateria;
    private javax.swing.JLabel jlbl_Profesor;
    private javax.swing.JLabel jlbl_TituloInscripcionMateriaProfesor;
    private javax.swing.JTextField jtf_ID_Alumno;
    // End of variables declaration//GEN-END:variables
}
