/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd.Vista;

import bd.Modelo.ManejoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author beto
 */
public class VentanaAltaMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form BajaMateria
     */
    public VentanaAltaMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTituloAltaMateria = new javax.swing.JLabel();
        jbCancelarAltaMateria = new javax.swing.JButton();
        jbAceptarAltaMateria = new javax.swing.JButton();
        jlbNombreAltaMateria = new javax.swing.JLabel();
        jtfNombreAltaMateria = new javax.swing.JTextField();

        jlbTituloAltaMateria.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jlbTituloAltaMateria.setText("Alta Materia");

        jbCancelarAltaMateria.setText("Cancelar");
        jbCancelarAltaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarAltaMateriaActionPerformed(evt);
            }
        });

        jbAceptarAltaMateria.setText("Aceptar");
        jbAceptarAltaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarAltaMateriaActionPerformed(evt);
            }
        });

        jlbNombreAltaMateria.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbTituloAltaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jlbNombreAltaMateria))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jbAceptarAltaMateria)
                        .addGap(45, 45, 45)
                        .addComponent(jbCancelarAltaMateria))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jtfNombreAltaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlbTituloAltaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jlbNombreAltaMateria)
                .addGap(18, 18, 18)
                .addComponent(jtfNombreAltaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptarAltaMateria)
                    .addComponent(jbCancelarAltaMateria))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarAltaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarAltaMateriaActionPerformed
        dispose();
    }//GEN-LAST:event_jbCancelarAltaMateriaActionPerformed

    private void jbAceptarAltaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarAltaMateriaActionPerformed
        ManejoBD manbd = new ManejoBD();
        try {
            manbd.altaMateria(this.jtfNombreAltaMateria.getText());            
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Un error ha ocurrido!: " + ex);
        }
    }//GEN-LAST:event_jbAceptarAltaMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAceptarAltaMateria;
    private javax.swing.JButton jbCancelarAltaMateria;
    private javax.swing.JLabel jlbNombreAltaMateria;
    private javax.swing.JLabel jlbTituloAltaMateria;
    private javax.swing.JTextField jtfNombreAltaMateria;
    // End of variables declaration//GEN-END:variables
}
