/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd.Vista;

import bd.Modelo.ManejoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author beto
 */
public class VentanaAltaAlumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form AltaAlumno
     */
    public VentanaAltaAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAltaNombreAlumno = new javax.swing.JLabel();
        jlAltaApellidoAlumno = new javax.swing.JLabel();
        jtfAltaNombreAlumno = new javax.swing.JTextField();
        jbAltaAlumno = new javax.swing.JButton();
        jbSalirAltaAlumno = new javax.swing.JButton();
        jtfAltaApellidoAlumno = new javax.swing.JTextField();
        jlAltaAlumnoTitulo = new javax.swing.JLabel();

        setResizable(true);
        setTitle("Alta Alumno");

        jlAltaNombreAlumno.setText("Nombre:");

        jlAltaApellidoAlumno.setText("Apellido:");

        jbAltaAlumno.setText("Aceptar");
        jbAltaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaAlumnoActionPerformed(evt);
            }
        });

        jbSalirAltaAlumno.setText("Cancelar");
        jbSalirAltaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirAltaAlumnoActionPerformed(evt);
            }
        });

        jlAltaAlumnoTitulo.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jlAltaAlumnoTitulo.setText("Alta Alumno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jlAltaAlumnoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlAltaNombreAlumno)
                            .addComponent(jlAltaApellidoAlumno))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jbAltaAlumno)
                                .addGap(18, 18, 18)
                                .addComponent(jbSalirAltaAlumno)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfAltaApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jtfAltaNombreAlumno))))))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlAltaAlumnoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAltaNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAltaNombreAlumno))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAltaApellidoAlumno)
                    .addComponent(jtfAltaApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAltaAlumno)
                    .addComponent(jbSalirAltaAlumno))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirAltaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirAltaAlumnoActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirAltaAlumnoActionPerformed

    private void jbAltaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaAlumnoActionPerformed
        ManejoBD manbd = new ManejoBD();
        try {
            manbd.altaAlumno(this.jtfAltaNombreAlumno.getText(), this.jtfAltaApellidoAlumno.getText());
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Un error ha ocurrido!: " + ex);
        }
    }//GEN-LAST:event_jbAltaAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAltaAlumno;
    private javax.swing.JButton jbSalirAltaAlumno;
    private javax.swing.JLabel jlAltaAlumnoTitulo;
    private javax.swing.JLabel jlAltaApellidoAlumno;
    private javax.swing.JLabel jlAltaNombreAlumno;
    private javax.swing.JTextField jtfAltaApellidoAlumno;
    private javax.swing.JTextField jtfAltaNombreAlumno;
    // End of variables declaration//GEN-END:variables
}
