/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd.Vista;

import bd.Modelo.ManejoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author beto
 */
public class VentanaAltaProfesor extends javax.swing.JInternalFrame {

    /**
     * Creates new form AltaProfesor
     */
    public VentanaAltaProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbl_TituloAltaProfesor = new javax.swing.JLabel();
        jlbl_NombreApellidoAltaProfesor = new javax.swing.JLabel();
        jbtn_AceptarAltaProfesor = new javax.swing.JButton();
        jbtn_CancelarAltaProfesor = new javax.swing.JButton();
        jtf_NombreApellidoAltaProfesor = new javax.swing.JTextField();

        jlbl_TituloAltaProfesor.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jlbl_TituloAltaProfesor.setText("Alta Profesor");

        jlbl_NombreApellidoAltaProfesor.setText("Nombre y apellido:");

        jbtn_AceptarAltaProfesor.setText("Aceptar");
        jbtn_AceptarAltaProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_AceptarAltaProfesorActionPerformed(evt);
            }
        });

        jbtn_CancelarAltaProfesor.setText("Cancelar");
        jbtn_CancelarAltaProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_CancelarAltaProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jlbl_TituloAltaProfesor)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlbl_NombreApellidoAltaProfesor)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_NombreApellidoAltaProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtn_AceptarAltaProfesor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn_CancelarAltaProfesor)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlbl_TituloAltaProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_NombreApellidoAltaProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_NombreApellidoAltaProfesor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_CancelarAltaProfesor)
                    .addComponent(jbtn_AceptarAltaProfesor))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_AceptarAltaProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_AceptarAltaProfesorActionPerformed
        ManejoBD manbd = new ManejoBD();
        try {
            manbd.altaProfesor(this.jtf_NombreApellidoAltaProfesor.getText());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaAltaProfesor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtn_AceptarAltaProfesorActionPerformed

    private void jbtn_CancelarAltaProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_CancelarAltaProfesorActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_CancelarAltaProfesorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_AceptarAltaProfesor;
    private javax.swing.JButton jbtn_CancelarAltaProfesor;
    private javax.swing.JLabel jlbl_NombreApellidoAltaProfesor;
    private javax.swing.JLabel jlbl_TituloAltaProfesor;
    private javax.swing.JTextField jtf_NombreApellidoAltaProfesor;
    // End of variables declaration//GEN-END:variables
}
